import daisyui from 'daisyui';
/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [daisyui],

  daisyui: {
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",

      // Custom curated themes
      {
        aurora: {
          primary: "#7dd3fc",
          secondary: "#a78bfa",
          accent: "#22d3ee",
          neutral: "#0b1220",
          "base-100": "#0f172a",
          "base-200": "#0b1220",
          "base-300": "#1f2937",
          info: "#38bdf8",
          success: "#10b981",
          warning: "#f59e0b",
          error: "#ef4444",
        },
      },
      {
        ocean: {
          primary: "#0ea5e9",
          secondary: "#22d3ee",
          accent: "#34d399",
          neutral: "#1f2937",
          "base-100": "#f8fafc",
          "base-200": "#e2e8f0",
          "base-300": "#cbd5e1",
          info: "#38bdf8",
          success: "#10b981",
          warning: "#f59e0b",
          error: "#ef4444",
        },
      },
      {
        midnight: {
          primary: "#6366f1",
          secondary: "#a855f7",
          accent: "#eab308",
          neutral: "#0b0f1a",
          "base-100": "#0b0f1a",
          "base-200": "#111827",
          "base-300": "#1f2937",
          info: "#60a5fa",
          success: "#22c55e",
          warning: "#f59e0b",
          error: "#f43f5e",
        },
      },
      {
        sunrise: {
          primary: "#f97316",
          secondary: "#fb7185",
          accent: "#f59e0b",
          neutral: "#1f2937",
          "base-100": "#fff7ed",
          "base-200": "#ffedd5",
          "base-300": "#fed7aa",
          info: "#38bdf8",
          success: "#10b981",
          warning: "#f59e0b",
          error: "#ef4444",
        },
      },
      {
        neon: {
          primary: "#22d3ee",
          secondary: "#f472b6",
          accent: "#a78bfa",
          neutral: "#0a0a0f",
          "base-100": "#0a0a0f",
          "base-200": "#111111",
          "base-300": "#1a1a1a",
          info: "#67e8f9",
          success: "#22c55e",
          warning: "#f59e0b",
          error: "#f43f5e",
        },
      },
      {
        matrix: {
          primary: "#22c55e",
          secondary: "#84cc16",
          accent: "#14b8a6",
          neutral: "#0a0f0a",
          "base-100": "#0a0f0a",
          "base-200": "#0f1a0f",
          "base-300": "#1a2a1a",
          info: "#34d399",
          success: "#22c55e",
          warning: "#eab308",
          error: "#ef4444",
        },
      },
      {
        moonlight: {
          primary: "#60a5fa",
          secondary: "#a78bfa",
          accent: "#f472b6",
          neutral: "#0b1220",
          "base-100": "#f1f5f9",
          "base-200": "#e2e8f0",
          "base-300": "#cbd5e1",
          info: "#93c5fd",
          success: "#34d399",
          warning: "#f59e0b",
          error: "#ef4444",
        },
      },
    ],
  },
}